# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "CRMH-RP3"

# A description of your site for meta tag, search engine results.
description: ""

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: ""

# Favicon
favicon: favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Calendar
    url: https://calendar.google.com/calendar/embed?src=0d83f07c7b3ffb3d043313721dfc303648ba5a91fd6034c547a47f40e8d6bc75%40group.calendar.google.com&ctz=Asia%2FHong_Kong
# The shortname for your Disqus site to enable comments.
disqus:

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "Copyright &copy; 2023 Martin To Sing Fung<br>Powered by Jekyll. Theme modified from Scriptor"
  has_social: false
  
# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/page:num/'

# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
